server:
  port: 8081
  #servlet:
    #context-path: /api
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT
    # username: root
    # password: 123456
    hikari:
      max-lifetime: 30000
  redis:
    # host: localhost
    # password: 123456
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 256
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
    timeout: 5000
    #security:
    #user:
    #name: user
    #password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.naown.entity
  # 取消Mysql-plus banner打印
  global-config:
    banner: false
naown:
  jwt:
    # 过期时间 (单位:秒)
    expire: 604800
    # 密钥 32位
    secret: sadasdwq1fas54fsad4w1saf45asfqwe
    # 头部 相当于一个常量
    header: Authorization