server:
  port: 8081
  #servlet:
    #context-path: /api
# DataSource Config
spring:
  autoconfigure:
    # 排除掉druid的默认自动配置
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 全局druid配置
      druid:
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      # 设置默认的数据源或者数据源组,默认值即为master 多数据源
      primary: master
      # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://8.131.60.144:3306/vue_admin?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT
          username: root
          password: 136957
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        #slave_1:
          #url: jdbc:mysql://xx.xx.xx.xx:3307/dynamic
          #username: root
          #password: 123456
          #driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT
    # username: root
    # password: 123456
  redis:
    host: 8.131.60.144
    password: 136957
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 256
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
    timeout: 5000
    #security:
    #user:
    #name: user
    #password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.naown.entity
  # 取消Mysql-plus banner打印
  global-config:
    banner: false
naown:
  jwt:
    # 过期时间 (单位:秒)
    expire: 604800
    # 密钥 32位
    secret: sadasdwq1fas54fsad4w1saf45asfqwe
    # 头部 相当于一个常量
    header: Authorization
# 测试远程提交回滚1